### ISSUE TITLE
No such file or directory: /daily_dialogue/data/train_data_frame.pkl

### ISSUE THREAD

**Issue by kwangje** [Ryanglambert/chatty#1]
Could you let me know the file format of "train_data_frame.pkl' 
AND
How can I get this resource?

It is a little bit confusing to me how to make the pickle file with the raw "Daily Dialog" corpus.
Could you explain a little bit about data preparation process?

**Comment by Ryanglambert** [comment]
from this repo: https://github.com/Ryanglambert/old_chatty

You actually want to use this file to make the model: 
https://github.com/Ryanglambert/old_chatty/blob/master/research/daily_dialogue/Speech%20Act%20Classifier%20Final.ipynb

And this file shows what happened to make the `train_data_frame.pkl`: 
https://github.com/Ryanglambert/old_chatty/blob/master/research/daily_dialogue/data.py

That is the right repo to look within. 

This repo we're in now was a mirror + some bad faith on my part to actually get it done. 

Let me know if you have any other questions!
